(ns {{NAMESPACE}}
  "Autogenerated scaffold for mission {{MISSION_ID}} and CodeType {{CODETYPE_IDENT}} (§4.7 evidence).")

(defn generated-handler
  []
  {:mission "{{MISSION_ID}}"
   :codetype "{{CODETYPE_IDENT}}"
   :note "Rendered from resources/codetype/sample_handler.clj.tpl"})
